language: bash
services: docker

script:
    - docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .
    - docker run -d -p 1527:1527 -v $(pwd)/dbs:/dbs $DOCKER_REPO:$TRAVIS_COMMIT
    - export CONTAINER_ID=$(docker ps | grep -F az82/docker-derby | cut -d' ' -f1)
    - sleep 3
    - docker logs $CONTAINER_ID | grep -F "started and ready"
    - nc -z localhost 1527
    - docker kill $CONTAINER_ID

after_success:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:$([[ "$TRAVIS_BRANCH" == "master" ]] && echo "latest" || echo $TRAVIS_BRANCH)
    - docker rmi $DOCKER_REPO:$TRAVIS_COMMIT
    - docker push $DOCKER_REPO
